// <auto-generated />
using System;
using BackupRestore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackupRestore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BackupDbContext))]
    partial class BackupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackupRestore.Core.Entities.BackupChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackupFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<long>("ChunkSize")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VaultPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BackupFileId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("BackupChunks");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.BackupFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("BackupJobId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BackupJobId", "RelativePath");

                    b.ToTable("BackupFiles");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BackupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("CopiedBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("FilesProcessed")
                        .HasColumnType("integer");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BackupId")
                        .IsUnique();

                    b.ToTable("BackupJobs");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackupFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackupJobId")
                        .HasColumnType("uuid");

                    b.Property<long>("BytesCompleted")
                        .HasColumnType("bigint");

                    b.Property<int>("LastCompletedChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BackupJobId", "BackupFileId")
                        .IsUnique();

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.JobEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobEvents");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.RestoreJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("RestorePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RestoredBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BackupId");

                    b.ToTable("RestoreJobs");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.BackupChunk", b =>
                {
                    b.HasOne("BackupRestore.Core.Entities.BackupFile", "BackupFile")
                        .WithMany("Chunks")
                        .HasForeignKey("BackupFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupFile");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.BackupFile", b =>
                {
                    b.HasOne("BackupRestore.Core.Entities.BackupJob", "BackupJob")
                        .WithMany("Files")
                        .HasForeignKey("BackupJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupJob");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.BackupFile", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("BackupRestore.Core.Entities.BackupJob", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
